input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/ml_project.pkl"
metric_path: "models/metrics.json"
output_folder: "data/raw/"
split_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
  n_estimators: 50
  max_depth: 10
  random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"